language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.2"
services:
  - riak 
before_install:
  - sudo service riak start
before_script:
  - touch spec/support/test_server.yml
  - echo "root: .riaktest" > spec/support/test_server.yml'
  - echo "source: /usr/sbin" >> spec/support/test_server.yml
  - "ulimit -n 2048"
script: bundle exec rspec spec